# Generated by Django 4.0.2 on 2022-02-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group_lvl', models.CharField(max_length=20, verbose_name='Group LVL')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('lvl', models.CharField(max_length=20, verbose_name='Personal LVL')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.IntegerField(null=7, verbose_name='Phone_number')),
                ('confirm_lesson', models.BooleanField(default=False)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('special_files', models.FileField(blank=True, null=True, upload_to='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
            ],
        ),
    ]
